# Generated by Django 2.0.5 on 2018-05-28 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('building_number', models.CharField(max_length=500)),
                ('postal_code', models.CharField(max_length=12)),
                ('locality', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(blank=True, verbose_name='date created')),
                ('created_by', models.CharField(blank=True, max_length=300)),
                ('updated_date', models.DateTimeField(blank=True, verbose_name='date updated')),
                ('updated_by', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StateJapan',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=200)),
                ('state_desc', models.CharField(blank=True, max_length=2000)),
                ('created_date', models.DateTimeField(blank=True, verbose_name='date created')),
                ('created_by', models.CharField(blank=True, max_length=300)),
                ('updated_date', models.DateTimeField(blank=True, verbose_name='date updated')),
                ('updated_by', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.StateJapan'),
        ),
    ]
