# Generated by Django 2.0.5 on 2018-05-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180529_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statejapan',
            name='created_by',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='statejapan',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='statejapan',
            name='updated_by',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='statejapan',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date updated'),
        ),
    ]
